### ISSUE TITLE
Game_Basic Structure

### ISSUE THREAD

**Issue by Handtrockner** [if-03-01-C-fall-2019/webapp-artificial-intelligence#3]
Program the basic structure of the game in Unity.

**Comment by bauepete** [comment]
Unity is definitely not a topic here. Keep stuck to Web Technologies.

**Comment by Handtrockner** [comment]
You can develop web apps with unity-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.05.20, 22:17 schrieb Peter Bauer <notifications@github.com>:

   
  Unity is definitely not a topic here. Keep stuck to Web Technologies.
